/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jbatik.project.panel;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileView;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;

public final class ProjectsLocationVisualPanel1 extends JPanel {

    List<FileObject> projectDirs;
    FileObject destination;
//    ProjectsLocationWizardPanel1 panel;

    public List<FileObject> getProjectDirs() {
        return projectDirs;
    }

    public FileObject getDestination() {
        return destination;
    }

    /**
     * Creates new form ProjectsLocationVisualPanel1
     */
    public ProjectsLocationVisualPanel1( //            ProjectsLocationWizardPanel1 panel
            ) {
        initComponents();
        projectDirs = new ArrayList<>();
//        this.panel = panel;
    }

    @Override
    public String getName() {
        return "Locations";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        oldProjectsTF = new javax.swing.JTextField();
        oldProjectBrowseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        destinationTF = new javax.swing.JTextField();
        newLocationButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ProjectsLocationVisualPanel1.class, "ProjectsLocationVisualPanel1.jLabel1.text")); // NOI18N

        oldProjectsTF.setText(org.openide.util.NbBundle.getMessage(ProjectsLocationVisualPanel1.class, "ProjectsLocationVisualPanel1.oldProjectsTF.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(oldProjectBrowseButton, org.openide.util.NbBundle.getMessage(ProjectsLocationVisualPanel1.class, "ProjectsLocationVisualPanel1.oldProjectBrowseButton.text")); // NOI18N
        oldProjectBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldProjectBrowseButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ProjectsLocationVisualPanel1.class, "ProjectsLocationVisualPanel1.jLabel2.text")); // NOI18N

        destinationTF.setText(org.openide.util.NbBundle.getMessage(ProjectsLocationVisualPanel1.class, "ProjectsLocationVisualPanel1.destinationTF.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(newLocationButton, org.openide.util.NbBundle.getMessage(ProjectsLocationVisualPanel1.class, "ProjectsLocationVisualPanel1.newLocationButton.text")); // NOI18N
        newLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newLocationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oldProjectsTF, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oldProjectBrowseButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(destinationTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newLocationButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(oldProjectsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldProjectBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(destinationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newLocationButton))
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    FileView projectView = new OldProjectDirView();
    private void oldProjectBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldProjectBrowseButtonActionPerformed
        // browse old projects, multiple selection enabled
        JFileChooser old = new JFileChooser();
        old.setCurrentDirectory(null);
        old.setDialogTitle("Select Old Project(s)");
        old.setMultiSelectionEnabled(true);
        old.setFileView(projectView);
        old.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (JFileChooser.APPROVE_OPTION == old.showOpenDialog(this)) {
            File[] projects = old.getSelectedFiles();
            projectDirs.clear();
            StringBuilder sb=new StringBuilder();
            for (File f : projects) {
                projectDirs.add(FileUtil.toFileObject(f));
                sb.append("\"").append(f.getName()).append("\";");
            }
            oldProjectsTF.setText(sb.toString());
        }
    }//GEN-LAST:event_oldProjectBrowseButtonActionPerformed

    private void newLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newLocationButtonActionPerformed
        // browse location for projects from converting operation
        JFileChooser newloc = new JFileChooser();
        newloc.setCurrentDirectory(null);
        newloc.setFileView(projectView);
        newloc.setDialogTitle("Select Destination Folder");
        newloc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        String path = this.destinationTF.getText();
        if (path.length() > 0) {
            File f = new File(path);
            if (f.exists()) {
                newloc.setSelectedFile(f);
            }
        }
        if (JFileChooser.APPROVE_OPTION == newloc.showOpenDialog(this)) {
            destination = FileUtil.toFileObject(newloc.getSelectedFile());
            destinationTF.setText(destination.getPath());
        }
//        panel.fireChangeEvent();

    }//GEN-LAST:event_newLocationButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField destinationTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newLocationButton;
    private javax.swing.JButton oldProjectBrowseButton;
    private javax.swing.JTextField oldProjectsTF;
    // End of variables declaration//GEN-END:variables
}
